baseURL = "https://example.com"
disablePathToLower = true
languageCode = "en-us"
title = "docter"
theme = "docter"

[params]
  # the name of your project and a link back to the home page
  home = "docter"
  # A small snippet of text above the sidebar:
  # subtitle = ""

  author = "org name"
  author_url= "https://github.com/edavidaja"

  # Point readers to your repo and invite them to edit pages 
  repo_host = "Gitlab"
  repo = "https://gitlab.com/edavidaja/docter"

  # Add a reference to a logo, which will appear in the top right
  # logourl = ""
  # logoalt = ""

  # Mention your hosting provider 
  hosted_on = "hosting provider"
  hosted_on_url= "#"

  # main sections
  # change the main section to set the directory where the top articles are sourced
  mainSections = ["post"]

  # brand color
  # brand_color = "#7300ac"