image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo -b "https://edavidaja.gitlab.io/docter/" -c "exampleSite/content" --config "exampleSite/config.toml" -t "docter" --themesDir ./..
  except:
  - master

pages:
  script:
  - hugo -b "https://edavidaja.gitlab.io/docter/" -c "exampleSite/content" --config "exampleSite/config.toml" -t "docter" --themesDir ./.. 
  artifacts:
    paths:
    - public
  only:
  - master
